CREATE DATABASE QLSV;
ON PRIMARY
CREATE TABLE LOP ( MaLop CHAR(5) NOT NULL PRIMARY KEY, 
    TenLop NVARCHAR(20) NOT NULL,
    SiSoDuKien INT,
    NgayKhaiGiang DATETIME );
CREATE TABLE SINHVIEN ( MaSV CHAR(5) NOT NULL PRIMARY KEY,
	TenHo NVARCHAR(40) NOT NULL,
	NgaySinh DATETIME,
    MaLop CHAR(5) NOT NULL FOREIGN KEY REFERENCES LOP(MaLop) );
CREATE TABLE MONHOC ( MaMH CHAR(5) NOT NULL PRIMARY KEY,
    TenMH NVARCHAR(30),
    SoTC INT );
CREATE TABLE KETQUA (
    MaSV CHAR(5) NOT NULL FOREIGN KEY REFERENCES SINHVIEN(MaSV),
    MaMH CHAR(5) NOT NULL FOREIGN KEY REFERENCES MONHOC(MaMH),
    Diem REAL,
    PRIMARY KEY (MaSV, MaMH) );
INSERT INTO LOP (MaLop, TenLop, SiSoDuKien, NgayKhaiGiang) 
VALUES ('NTMDT', 'TMDT19', 85, '2024-12-23');

INSERT INTO MONHOC (MaMH, TenMH, SoTC) 
VALUES ('CSDL', 'Co So Du Lieu', 3), 
       ('TCC', 'Toan Cao Cap', 2);

INSERT INTO SINHVIEN (MaSV, TenHo, NgaySinh, MaLop) 
VALUES ('23713', 'Nguyen Duc Loi', '2005-10-18', 'TMDT'), 
       ('23714', 'Nguyen Duc L', '2005-10-18', 'TMDT');

INSERT INTO KETQUA (MaSV, MaMH, Diem) 
VALUES ('23713', 'CSDL', 8.5), 
       ('23713', 'TCC', 9),
	   ('23714', 'TCC', 9);
SELECT * FROM LOP WHERE MaLop = 'NTMDT';
SELECT * FROM SINHVIEN WHERE MaSV IN ('23713', '23714');
SELECT * FROM LOP WHERE MaLop = 'TMDT';
SELECT * FROM KETQUA WHERE MaSV IN ('23713', '23714');

